### PR TITLE
pack: Simplify integer conversion.

### PR DESCRIPTION
**Pull request by tsuna**
Convert the `int64` to a `uint64` via a standard conversion rather than with `unsafe`.

### CODE REVIEW

**Comment by joshlf** [comment]
I do it this way a) to make sure that the value isn't modified at all (I'm pretty sure the semantics of conversion are fine in this case, but I'd rather be safe than sorry) and b) for the minor performance gains (although to be fair I'm pretty sure any compiler worth its salt would optimize that out if it really can't modify the underlying bits). Thoughts?

**Comment by tsuna** [comment]
The [conversion semantics are well defined](https://golang.org/ref/spec#Conversions) and I'm pretty certain that the roundtrip via `unsafe.Pointer` is slower.  At least with Go 1.4.1 it [compiles into more instructions](https://goo.gl/7jSVJy).

**Comment by joshlf** [comment]
Oh weird. I'd always assumed that the compiler special-cased unsafe.Pointer
conversions and elided them from the actual binary. And I saw the semantic
documentation, but to be honest it's a tad vague. I'll take a look and see
if we have any negative number tests; if it passes those I'm happy.

**Comment by tsuna** [comment]
Yeah the Go compiler doesn't optimize anything at all – which is quite amazing given how fast the code runs.  There is a bunch of work being done on the SSA IR (Static Single-Assignment Intermediate Representation) that will allow the Go compiler to become an optimizing compiler.  I think this will first ship in Go 1.6 (for amd64 only in the beginning).

**Comment by joshlf** [comment]
Oh wow. That's pretty surprising.

**Comment by joshlf** [comment]
OK, I pushed a very minor change to add a little more negative signed value testing. It turns out there's already a decent amount of testing with regards to overflow checking and such, so I think we're good.

**Pull request merged**
