### PR TITLE
Fix an integer overflow during packer construction.

### PR DESCRIPTION
**Pull request by tsuna**

### CODE REVIEW

**Comment by joshlf** [comment]
Hey, thanks for the PR; looks good! I'm just going to pull and test to make sure everything's good and then I'll merge it.

**Comment by joshlf** [comment]
Actually, would you mind adding yourself to the AUTHORS file and resubmitting the PR?

**Comment by tsuna** [comment]
Done, I amended my commit.

Another thing I've been tempted to add is the ability to specify the endianness to use, with the `gopack` tag.  Would you be interested?

I'm using `gopack` to decode some crappy protocol-designed-by-committee, and found it very useful.  Of course most protocols use network endianness (big endian).

**Comment by joshlf** [comment]
When you say endianness, do you mean bit or byte endianness? I'd definitely be interested, but we should discuss the design further. There are a number of ways to go about this, and there are some subtle design considerations.

**Comment by joshlf** [comment]
Maybe submit an issue and we can discuss there?

**Comment by tsuna** [comment]
Sure, I'll put out a proposal.

**Comment by joshlf** [comment]
Actually, I just realized: why int and not uint64, as we were already using? Not that anyone is going to try making a 2^31- or 2^63-byte packer, but still...

**Comment by tsuna** [comment]
Yeah I picked `int` out of simplicity.  Feel free to change it to whatever pleases your heart.  :)

**Comment by joshlf** [comment]
OK, just making sure there wasn't a specific reason. Will do.

**Pull request merged**
